
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: djangousr
      POSTGRES_PASSWORD: django_password
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.26.3
    container_name: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
  backend:  
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend  
    restart: always
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
  
  streamlit_ui:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    container_name: streamlit_ui
    restart: always
    depends_on:
      - backend  
    ports:
      - "8501:8501"
volumes:
  postgres_data: